spring.datasource.url: jdbc:mysql://localhost:3306/social_network?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
spring.datasource.username: root
spring.datasource.password: password
spring.jpa.hibernate.ddl-auto: update
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

jwt:
  token:
    secret: secret
    expired: 3600000

spring.mail.host: smtp.yandex.ru
spring.mail.username: email@yandex.ru
spring.mail.password: password
spring.mail.port: 465
spring.mail.protocol: smtps
mail.debug: true